---
title: "Rosenbluh Sim"
author: "Timothy Daley"
output: html_document
---

```{r}
rm(list = ls())
Rosenbluh2017CRISPRkoANDi = read.table(file = "~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoANDi.txt", header = TRUE)
set.seed(123)
Rosenbluh2017CRISPRko = Rosenbluh2017CRISPRkoANDi[which(Rosenbluh2017CRISPRkoANDi$Category %in% c("exon", "control")), c(1:9, 10:11)]
dim(Rosenbluh2017CRISPRko)
hist(rowSums(Rosenbluh2017CRISPRko[,c("DNA_Pool", "HT29_Cas9_pLX311_Rep1", "HT29_Cas9_pLX311_Rep2")]), breaks = 100)
Rosenbluh2017CRISPRko = Rosenbluh2017CRISPRko[-which(rowSums(Rosenbluh2017CRISPRko[,c("DNA_Pool", "HT29_Cas9_pLX311_Rep1", "HT29_Cas9_pLX311_Rep2")]) < 300), ]
dim(Rosenbluh2017CRISPRko)
```
```{r}
library(DESeq2)
library(ggplot2)
library(ggjoy)
gene.ids = Rosenbluh2017CRISPRko$Gene
gene.counts = c(table(gene.ids[-which(is.na(gene.ids))]))
library(fitdistrplus)
gene.counts.nb.fit = fitdist(gene.counts, "nbinom") 
gene.counts.nb.fit
neg.gene.counts = rnbinom(3*length(gene.counts), 
                          mu = gene.counts.nb.fit$estimate[2], 
                          size = gene.counts.nb.fit$estimate[1])
Rosenbluh2017CRISPRko.negctrl = Rosenbluh2017CRISPRko[which(is.na(Rosenbluh2017CRISPRko$Gene)), ]
n.negctrl = dim(Rosenbluh2017CRISPRko.negctrl)[1]
Rosenbluh2017CRISPRko.neg.sim = c()
for(i in 1:length(neg.gene.counts)){
  for(j in 1:neg.gene.counts[i]){
    rand.index = sample.int(n.negctrl, 1)
    Rosenbluh2017CRISPRko.neg.sim = rbind(Rosenbluh2017CRISPRko.neg.sim, 
                                         c("sim", paste0("sim", i), "NA", "sim", "NA", 0, 0, "+",
                                           rnbinom(1, mu = Rosenbluh2017CRISPRko.negctrl$DNA_Pool[rand.index], size = 200),
                                           rnbinom(1, mu = Rosenbluh2017CRISPRko.negctrl$HT29_Cas9_pLX311_Rep1[rand.index], size = 200),
                                           rnbinom(1, mu = Rosenbluh2017CRISPRko.negctrl$HT29_Cas9_pLX311_Rep2[rand.index], size = 200)))
  }
}
Rosenbluh2017CRISPRko.sim = data.frame(Cell_line = c(sapply(Rosenbluh2017CRISPRko$Cell_line, toString), Rosenbluh2017CRISPRko.neg.sim[,1]),
                                      Gene = c(sapply(Rosenbluh2017CRISPRko$Gene, toString), Rosenbluh2017CRISPRko.neg.sim[,2]),
                                      Spacer = c(sapply(Rosenbluh2017CRISPRko$Spacer, toString), paste0("sim", 1:length(Rosenbluh2017CRISPRko.neg.sim[,3]))),
                                      Category = c(sapply(Rosenbluh2017CRISPRko$Category, toString), Rosenbluh2017CRISPRko.neg.sim[,4]), 
                                      Chr = c(sapply(Rosenbluh2017CRISPRko$Chr, toString), Rosenbluh2017CRISPRko.neg.sim[,5]),
                                      Start = c(Rosenbluh2017CRISPRko$Start, Rosenbluh2017CRISPRko.neg.sim[,6]),
                                      End = c(Rosenbluh2017CRISPRko$End, Rosenbluh2017CRISPRko.neg.sim[,7]),
                                      Strand = c(sapply(Rosenbluh2017CRISPRko$Strand, toString), Rosenbluh2017CRISPRko.neg.sim[,8]),
                                      DNA_Pool = as.numeric(c(Rosenbluh2017CRISPRko$DNA_Pool, Rosenbluh2017CRISPRko.neg.sim[,9])),
                                      HT29_Cas9_pLX311_Rep1 = as.numeric(c(Rosenbluh2017CRISPRko$HT29_Cas9_pLX311_Rep1, Rosenbluh2017CRISPRko.neg.sim[,10])),
                                      HT29_Cas9_pLX311_Rep2 = as.numeric(c(Rosenbluh2017CRISPRko$HT29_Cas9_pLX311_Rep2, Rosenbluh2017CRISPRko.neg.sim[,11])))
Rosenbluh2017CRISPRko.sim = Rosenbluh2017CRISPRko.sim[which(rowSums(Rosenbluh2017CRISPRko.sim[,9:11]) > 300), ]
Rosenbluh2017CRISPRko.sim.counts = Rosenbluh2017CRISPRko.sim[,c(9:11)]
rownames(Rosenbluh2017CRISPRko.sim.counts) = Rosenbluh2017CRISPRko.sim$Spacer
coldata = data.frame(condition = factor(c(0, 1, 1)))
rownames(coldata) = colnames(Rosenbluh2017CRISPRko.sim.counts)
Rosenbluh2017CRISPRko.sim.DESeq = DESeq2::DESeqDataSetFromMatrix(countData = Rosenbluh2017CRISPRko.sim.counts, 
                                                                colData = coldata, 
                                                                design = ~ condition)
Rosenbluh2017CRISPRko.sim.DESeq = DESeq2::DESeq(Rosenbluh2017CRISPRko.sim.DESeq)
Rosenbluh2017CRISPRko.sim.DESeq = DESeq2::results(Rosenbluh2017CRISPRko.sim.DESeq)
Rosenbluh2017CRISPRko.sim.DESeq.log2fc = Rosenbluh2017CRISPRko.sim.DESeq$log2FoldChange
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene = Rosenbluh2017CRISPRko.sim$Gene
length(Rosenbluh2017CRISPRko.sim.DESeq.log2fc[which(Rosenbluh2017CRISPRko.sim$Category != "control")])
length(Rosenbluh2017CRISPRko.sim.DESeq.log2fc)
dim(Rosenbluh2017CRISPRko.sim)
```
```{r}
Rosenbluh2017CRISPRko.sim.essential = data.frame(gene = unique(Rosenbluh2017CRISPRko.sim$Gene), 
                                                essential = 1 - grepl("sim", unique(Rosenbluh2017CRISPRko.sim$Gene)))
Rosenbluh2017CRISPRko.sim.essential = Rosenbluh2017CRISPRko.sim.essential[-which(Rosenbluh2017CRISPRko.sim.essential$gene == "NA"), ]
write.table(Rosenbluh2017CRISPRko.sim[ , c("Spacer", "Gene", "DNA_Pool", "HT29_Cas9_pLX311_Rep1", "HT29_Cas9_pLX311_Rep2")],  
            file = "~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSim.txt",
            quote = FALSE, sep = "\t", row.names = FALSE, col.names = TRUE)
write.table(Rosenbluh2017CRISPRko.sim$Spacer[which(Rosenbluh2017CRISPRko.sim$Category == "control")],  
            file = "~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNegativeControl.txt",
            quote = FALSE, sep = "\n", row.names = FALSE, col.names = FALSE)
```
```{r}
system("mageck test -k ~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSim.txt -t HT29_Cas9_pLX311_Rep1,HT29_Cas9_pLX311_Rep2 --output-prefix ~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl")
Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl.gene_summary = read.table(file = "~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl.gene_summary.txt", header = TRUE)
Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl.gene_summary = Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl.gene_summary[match(Rosenbluh2017CRISPRko.sim.essential$gene, Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl.gene_summary$id), ]
dim(Rosenbluh2017CRISPRkoSimMageckRraNoNegCtrl.gene_summary)
```
```{r}
system("mageck test -k ~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSim.txt -t HT29_Cas9_pLX311_Rep1,HT29_Cas9_pLX311_Rep2 --output-prefix ~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckRra --control-sgrna ~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNegativeControl.txt")
Rosenbluh2017CRISPRkoSimMageckRra.gene_summary = read.table(file = "~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckRra.gene_summary.txt", header = TRUE)
Rosenbluh2017CRISPRkoSimMageckRra.gene_summary = Rosenbluh2017CRISPRkoSimMageckRra.gene_summary[match(Rosenbluh2017CRISPRko.sim.essential$gene, Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$id), ]
dim(Rosenbluh2017CRISPRkoSimMageckRra.gene_summary)
```
```{r}
system("mageck mle -k Rosenbluh2017CRISPRkoSim.txt -d design_matrix_ko.txt --output-prefix Rosenbluh2017CRISPRkoSimMageckMle --control-sgrna Rosenbluh2017CRISPRkoSimNegativeControl.txt")
Rosenbluh2017CRISPRkoSimMageckMle.gene_summary = read.table(file = "~/sgRNA/sgRNA2Groups/data/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckMle.gene_summary.txt", header = TRUE)
dim(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary)
dim(Rosenbluh2017CRISPRko.sim.essential)
Rosenbluh2017CRISPRkoSimMageckMle.gene_summary = Rosenbluh2017CRISPRkoSimMageckMle.gene_summary[match(Rosenbluh2017CRISPRko.sim.essential$gene, Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Gene), ]
dim(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary)
```



```{r}
x = data.frame(log2fc = Rosenbluh2017CRISPRko.sim.DESeq.log2fc, category = Rosenbluh2017CRISPRko.sim$Category)

ggplot(x, aes(x = log2fc, colour = category)) + geom_histogram(aes(y = ..density.., fill = category), alpha = 0.5, bins = 50, position = "identity")+  theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNegativeControlVsNegativeGenesVsPositiveGenesHist.pdf')
#ggplot(x, aes(x = log2fc, colour = category)) + geom_histogram(aes(y = ..density.., fill = category), alpha = 0.5, bins = 50, position = "identity")+  theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
#dev.off()

#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNegativeControlVsNegativeGenesVsPositiveGenesJoyplot.pdf')
ggplot(x, aes(x = log2fc, y = category)) + geom_joy(scale = 0.85) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
#dev.off()
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNegativeControlVsNegativeGenesVsP#ositiveGenesJoyplot.pdf')
#ggplot(x, aes(x = log2fc, y = category)) + geom_joy(scale = 0.85) + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
#dev.off()
```
```{r}
devtools::install_github("timydaley/CRISPhieRmix", force = TRUE)
library(CRISPhieRmix)
geneIds = Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene[-which(Rosenbluh2017CRISPRko.sim$Category == "control")]
geneIds = factor(geneIds, levels = unique(geneIds))
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix = CRISPhieRmix(x = Rosenbluh2017CRISPRko.sim.DESeq.log2fc[-which(Rosenbluh2017CRISPRko.sim$Category == "control")],
                                                                  negCtrl = Rosenbluh2017CRISPRko.sim.DESeq.log2fc[which(Rosenbluh2017CRISPRko.sim$Category == "control")],
                                                                  geneIds = geneIds,
                                                                  mu = -5, sigma = 2, VERBOSE = TRUE, PLOT = TRUE, nMesh = 100)
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$skewtFit$dp
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$mu
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$sigma
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq
globalFdr = sapply(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr, function(x) mean(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr <= x)]))
```
```{r}
x = Rosenbluh2017CRISPRko.sim.DESeq.log2fc[-which(Rosenbluh2017CRISPRko.sim$Category == "control")]
b = seq(from = min(x) - 0.1, to = max(x) + 0.1, length = 81)
hist(x, breaks = b, probability = TRUE, main = "mixture fit to observations", ylim = c(0, 1.1))
lines(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq*dnorm(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$mu, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$sigma), lwd = 2, col = "dodgerblue")
lines(b, (1 - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq)*sn::dst(b, dp = Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$skewtFit$dp), col = "red", lwd  = 2)
lines(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq*dnorm(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$mu, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$sigma) + (1 - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq)*sn::dst(b, dp = Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$skewtFit$dp), lwd = 2, col = "darkviolet")
legend("topleft", legend = c("negative control fit", "positive fit", "mixture fit"), lwd = 2, col = c("red", "dodgerblue", "darkviolet"))

#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimGeneTargetingmixFit.pdf')
#hist(x, breaks = b, probability = TRUE, main = "mixture fit to observations", ylim = c(0, 1.1))
#lines(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq*dnorm(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$mu, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$sigma), lwd = 2, col = "dodgerblue")
#lines(b, (1 - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq)*exp(apply(t(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_coefficients[-1]*t(poly(b, degree = length(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_coefficients) - 1, raw = TRUE))), 1, sum) + Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_coefficients[1] - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_log_norm_factor), col = "red", lwd  = 2)
#lines(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq*dnorm(b, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$mu, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$sigma) + (1 - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$pq)*exp(apply(t(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_coefficients[-1]*t(poly(b, degree = length(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_coefficients) - 1, raw = TRUE))), 1, sum) + Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_coefficients[1] - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$mixFit$null_log_norm_factor), lwd = 2, col = "darkviolet")
#legend("topleft", legend = c("negative control fit", "positive fit", "mixture fit"), lwd = 2, col = c("red", "dodgerblue", "darkviolet"))
#dev.off()

Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix = CRISPhieRmix(x = Rosenbluh2017CRISPRko.sim.DESeq.log2fc[-which(Rosenbluh2017CRISPRko.sim$Category == "control")], 
                                                            geneIds = geneIds, 
                                                            mu = -2, sigma = 1, nMesh = 100)
```

```{r}
MannWhitneyPvals = sapply(unique(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene), function(g) return(wilcox.test(x = Rosenbluh2017CRISPRko.sim.DESeq.log2fc[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene == g)], Rosenbluh2017CRISPRko.sim.DESeq.log2fc[which(Rosenbluh2017CRISPRko.sim$Category == "control")], paired = FALSE)$p.value))
names(MannWhitneyPvals) = unique(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene)
MannWhitneyPvals = MannWhitneyPvals[-which(names(MannWhitneyPvals) == "NA")]
head(MannWhitneyPvals)
tail(MannWhitneyPvals)
hist(MannWhitneyPvals, breaks = 40, col = "grey")

MannWhitneyFdrs = p.adjust(MannWhitneyPvals, method = "BH")
head(sort(MannWhitneyFdrs, decreasing = TRUE), 20)

top3MannWhitneyPval <- function(x, negCtrl){
  top3x = head(sort(x, decreasing = FALSE), 3)
  topNegCtrl = head(sort(negCtrl, decreasing = FALSE), round(3*length(negCtrl)/length(x)))
  return(wilcox.test(top3x, topNegCtrl, paired = FALSE)$p.value)
}
top3MannWhitneyPvals = sapply(unique(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene), function(g) return(top3MannWhitneyPval(x = Rosenbluh2017CRISPRko.sim.DESeq.log2fc[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene == g)], negCtrl =  Rosenbluh2017CRISPRko.sim.DESeq.log2fc[which(Rosenbluh2017CRISPRko.sim$Category == "control")])))
names(top3MannWhitneyPvals) = unique(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.gene)
top3MannWhitneyPvals = top3MannWhitneyPvals[-which(names(top3MannWhitneyPvals) == "NA")]
top3MannWhitneyFdrs = p.adjust(top3MannWhitneyPvals, method = "BH")
head(sort(top3MannWhitneyFdrs, decreasing = FALSE), 20)
```

```{r}
# empirical mix
sum(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr < 0.1)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr < 0.1)])
sum(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr < 0.2)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr < 0.2)])

#normal mix
sum(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr < 0.2)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr < 0.2)])

# mageck wald test
sum(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.fdr < 0.1)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.fdr < 0.1)])
sum(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.fdr < 0.2)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.fdr < 0.2)])

# mageck permutation test
sum(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr < 0.1)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr < 0.1)])
sum(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr < 0.2)
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr < 0.2)])


fdr.curve <- function(thresh, fdrs, baseline){
  w = which(fdrs < thresh)
  if(length(w) > 0){
    return(sum(1 - baseline[w])/length(w))
  }
  else{
    return(NA)
  }
}
s = seq(from = 0, to = 1, length = 101)
#f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$neg.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
#plot(s[na.omit(f)], f[na.omit(f)], type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "MAGeCK RRA")

length(intersect(Rosenbluh2017CRISPRko.sim.essential$gene[which(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr < 0.1)], Rosenbluh2017CRISPRko.sim.essential$gene[which(globalFdr < 0.1)]))
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckMleWaldEmpiricalVsEstimatedFDR.pdf')
#plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "MAGeCK MLE", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "deeppink")
#abline(0, 1, lty = 2)
#dev.off()

f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "MAGeCK MLE permutation Fdr", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "deeppink")
abline(0, 1, lty = 2)
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckMleEmpiricalVsEstimatedFDR.pdf')
#plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "MAGeCK MLE", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "deeppink")
#abline(0, 1, lty = 2)
#dev.off()


length(which(globalFdr < 0.1))
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(globalFdr < 0.1)])
length(which(globalFdr < 0.2))
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(globalFdr < 0.2)])

f = sapply(s, function(t) fdr.curve(t, globalFdr, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "CRISPhieRmix", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "dodgerblue")
abline(0, 1, lty = 2)
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimCRISPhieRmixEmpiricalVsEstimatedFDR.pdf')
#plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "CRISPhieRmix", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "dodgerblue")
#abline(0, 1, lty = 2)
#dev.off()


Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.fdr = sapply(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr, function(x) mean(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr <= x)]))
length(which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.fdr < 0.1))
sum(Rosenbluh2017CRISPRko.sim.essential$essential[which(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.fdr < 0.1)])

f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "Normal FDR", main = "normal mix", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "dodgerblue")
abline(0, 1, lty = 2)

f = sapply(s, function(t) fdr.curve(t, MannWhitneyFdrs, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "Normal FDR", main = "Mann-Whitney", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "chartreuse")
abline(0, 1, lty = 2)

f = sapply(s, function(t) fdr.curve(t, top3MannWhitneyFdrs, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "Normal FDR", main = "top 3 Mann-Whitney", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "chartreuse")
abline(0, 1, lty = 2)


library(RColorBrewer)
cols = brewer.pal(6, "Set1")
f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "controlling the false discovery rate", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = cols[3])
f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$neg.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
lines(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), lwd = 2, col = cols[4])
f = sapply(s, function(t) fdr.curve(t, MannWhitneyFdrs, Rosenbluh2017CRISPRko.sim.essential$essential))
lines(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), lwd = 2, col = cols[1])
f = sapply(s, function(t) fdr.curve(t, globalFdr, Rosenbluh2017CRISPRko.sim.essential$essential))
lines(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), lwd = 2, col = cols[2])
legend("bottomright", legend = c("MAGeCK MLE", "MAGeCK RRA", "Mann-Whitney", "CRISPhieRmix"), col = cols[c(3, 4, 1, 2)], lty = 1)
abline(0, 1)

pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimEmpiricalVsEstimatedFDR.pdf')
f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "empirical FDR", main = "controlling the false discovery rate", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = cols[3])
f = sapply(s, function(t) fdr.curve(t, Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$neg.fdr, Rosenbluh2017CRISPRko.sim.essential$essential))
lines(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), lwd = 2, col = cols[4])
f = sapply(s, function(t) fdr.curve(t, MannWhitneyFdrs, Rosenbluh2017CRISPRko.sim.essential$essential))
lines(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), lwd = 2, col = cols[1])
f = sapply(s, function(t) fdr.curve(t, globalFdr, Rosenbluh2017CRISPRko.sim.essential$essential))
lines(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), lwd = 2, col = cols[2])
legend("bottomright", legend = c("MAGeCK MLE", "MAGeCK RRA", "Mann-Whitney", "CRISPhieRmix"), col = cols[c(3, 4, 1, 2)], lty = 1)
abline(0, 1)
dev.off()


#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNormalMixEmpiricalVsEstimatedFDR.pdf')
#plot(c(0, s[!is.na(f)]), c(0, f[!is.na(f)]), type = "l", xlab = "estimated FDR", ylab = "Normal FDR", main = "normal mix", xlim = c(0, 1), ylim = c(0, 1), lwd = 2, col = "dodgerblue")
#abline(0, 1, lty = 2)
#dev.off()
```

```{r}
hist(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr, breaks = 40, col = "grey", main = "CRISPhieRmix local fdrs")
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimCRISPhieRmixFdrHist.pdf')
#hist(1 - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$score, breaks = 40, col = "grey")
#dev.off()

hist(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr, breaks = 40, col = "grey", main = "normal hier mix local fdrs")
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimNormalMixFdrHist.pdf')
#hist(1 - Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$score, breaks = 40, col = "grey")
#dev.off()

hist(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.p.value, breaks = 40, col = "grey", main = "MAGeCK MLE permutation pvals")
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckMleFdrHist.pdf')
#hist(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.p.value, breaks = 40, col = "grey")
#dev.off()

hist(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.p.value, breaks = 40, col = "grey", main = "MAGeCK Wald p values")
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckMleWaldFdrHist.pdf')
#hist(Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.p.value, breaks = 40, col = "grey")
#dev.off()

hist(Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$neg.p.value, breaks = 40, col = "grey", main = "MAGeCK RRA pvals")
#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimMageckRraFdrHist.pdf')
#hist(Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$neg.p.value, breaks = 40, col = "grey")
#dev.off()
```


```{r}
library(pROC)
# empirical mix
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix$locfdr, auc = TRUE)
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc
# normal mix
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix$locfdr, auc = TRUE)
Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc
# Mageck mle wald
Rosenbluh2017CRISPRkoSimMageckMleWald.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.wald.p.value, auc = TRUE)
Rosenbluh2017CRISPRkoSimMageckMleWald.roc
# mageck mle permuation
Rosenbluh2017CRISPRkoSimMageckMle.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, Rosenbluh2017CRISPRkoSimMageckMle.gene_summary$Cas9.p.value, auc = TRUE)
Rosenbluh2017CRISPRkoSimMageckMle.roc
# mageck rra
Rosenbluh2017CRISPRkoSimMageckRra.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, Rosenbluh2017CRISPRkoSimMageckRra.gene_summary$neg.p.value, auc = TRUE)
Rosenbluh2017CRISPRkoSimMageckRra.roc
#Mann-Whitney
MannWhitneyFdrs.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, MannWhitneyFdrs, auc = TRUE)
MannWhitneyFdrs.roc
# top 3 Mann-Whitney
top3MannWhitneyFdrs.roc = roc(Rosenbluh2017CRISPRko.sim.essential$essential, top3MannWhitneyFdrs, auc = TRUE)
top3MannWhitneyFdrs.roc



library(RColorBrewer)
cols = brewer.pal(6, "Set1")
plot(Rosenbluh2017CRISPRkoSimMageckMle.roc, col = cols[3], lwd = 2, xlim = c(0, 1), ylim = c(0, 1), main = "ROC curves")
lines(Rosenbluh2017CRISPRkoSimMageckRra.roc, col = cols[4], lwd = 3, lty = 3)
lines(MannWhitneyFdrs.roc, col = cols[1], lwd = 2, lty = 4)
lines(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc, col = cols[2], lwd = 2)
#lines(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc, col = cols[4], lwd = 2, lty = 5)
#lines(top3MannWhitneyFdrs.roc, col = cols[6], lwd = 2, lty = 7)
legend("bottomleft", legend = c(paste0("MAGeCK MLE (AUC = ", round(Rosenbluh2017CRISPRkoSimMageckMle.roc$auc, digits = 3), ")"), 
                                paste0("MAGeCK RRA (AUC = ", round(Rosenbluh2017CRISPRkoSimMageckRra.roc$auc, digits = 3), ")"), 
                                paste0("Mann-Whitney (AUC = ", round(MannWhitneyFdrs.roc$auc, digits = 3), ")"),
                                paste0("CRISPhieRmix (AUC = ", round(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc$auc, digits = 3), ")")
                                #paste0("normal hier mix (AUC = ", round(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc$auc, digits = 3), ")"), 
                                
                                #paste0("top 3 Mann-Whitney (AUC = ", round(top3MannWhitneyFdrs.roc$auc, digits = 3), ")")
                                ),  lwd = 2, col = cols[c(3, 4, 1, 2)])
pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimRocCurvesNew.pdf')
plot(Rosenbluh2017CRISPRkoSimMageckMle.roc, col = cols[3], lwd = 2, xlim = c(0, 1), ylim = c(0, 1), main = "ROC curves")
lines(Rosenbluh2017CRISPRkoSimMageckRra.roc, col = cols[4], lwd = 3, lty = 3)
#lines(Rosenbluh2017CRISPRkoSimMageckMleWald.roc, col = cols[2], lwd = 3, lty = 3)
lines(MannWhitneyFdrs.roc, col = cols[1], lwd = 2, lty = 4)
lines(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc, col = cols[2], lwd = 2)
#lines(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc, col = cols[4], lwd = 2, lty = 5)
#lines(top3MannWhitneyFdrs.roc, col = cols[6], lwd = 2, lty = 7)
legend("bottomleft", legend = c(paste0("MAGeCK MLE (AUC = ", round(Rosenbluh2017CRISPRkoSimMageckMle.roc$auc, digits = 3), ")"), 
                                paste0("MAGeCK RRA (AUC = ", round(Rosenbluh2017CRISPRkoSimMageckRra.roc$auc, digits = 3), ")"), 
                                paste0("Mann-Whitney (AUC = ", round(MannWhitneyFdrs.roc$auc, digits = 3), ")"),
                                paste0("CRISPhieRmix (AUC = ", round(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc$auc, digits = 3), ")")
                                #paste0("normal hier mix (AUC = ", round(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc$auc, digits = 3), ")"), 
                                
                                #paste0("top 3 Mann-Whitney (AUC = ", round(top3MannWhitneyFdrs.roc$auc, digits = 3), ")")
                                ),  lwd = 2, col = cols[c(3, 4, 1, 2)])
dev.off()

#pdf('~/sgRNA/sgRNA2Groups/tex_writing/figures/Rosenbluh2017/Rosenbluh2017CRISPRkoSimRocCurves.pdf')
#plot(Rosenbluh2017CRISPRkoSimMageckMle.roc, col = "deeppink", lwd = 2, lty = 2, xlim = c(0, 1), ylim = c(0, 1), main = "ROC curves")
#lines(Rosenbluh2017CRISPRkoSimMageckMleWald.roc, col = "red", lwd = 3, lty = 2)
#lines(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc, col = "dodgerblue", lwd = 2, lty = 4)
#lines(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc, col = "darkblue", lwd = 2, lty = 5)
#legend("bottomleft", legend = c(paste0("MAGeCK MLE (AUC = ", round(Rosenbluh2017CRISPRkoSimMageckMle.roc$auc, digits = 3), ")"), paste0("MAGeCK Wald MLE (AUC = ", round(Rosenbluh2017CRISPRkoSimMageckMleWald.roc$auc, digits = 3), ")"), paste0("CRISPhieRmix (AUC = ", round(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.CRISPhieRmix.roc$auc, digits = 3), ")"), paste0("normal hier mix (AUC = ", round(Rosenbluh2017CRISPRko.sim.DESeq.log2fc.NormalMix.roc$auc, digits = 3), ")")), lty = c(2, 3, 4, 5), lwd = 2, col = c("deeppink", "red", "dodgerblue", "darkblue"))
#dev.off()
```



